import type { Account } from "@/types/account-balance";

export const fakeUsers: Account[] = [
  {
    username: "quocviet2208",
    loginName: "quocviet2208",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 4.38,
    unpaidBet: 50.0,
    eWalletPromotion: "Register Bonus",
  },
  {
    username: "Vung1988",
    loginName: "Vung1988",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.44,
    unpaidBet: 0.6,
    eWalletPromotion: "Deposit Bonus",
  },
  {
    username: "Loanle1985",
    loginName: "Loanle1985",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.88,
    unpaidBet: 0.4,
    eWalletPromotion: "Register Bonus",
  },
  {
    username: "aaaazzz",
    loginName: "aaaazzz",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.0,
    unpaidBet: 0.0,
    eWalletPromotion: "Deposit Bonus",
  },
  {
    username: "Kakalx",
    loginName: "Kakalx",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.0,
    unpaidBet: 0.0,
    eWalletPromotion: "Welcome Offer",
  },
  {
    username: "Nhoctanbinh",
    loginName: "Nhoctanbinh",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.0,
    unpaidBet: 0.0,
    eWalletPromotion: "Cashback",
  },
  {
    username: "Nghiatoloi",
    loginName: "Nghiatoloi",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.09,
    unpaidBet: 0.0,
    eWalletPromotion: "Register Bonus",
  },
  {
    username: "Thanhqt98",
    loginName: "Thanhqt98",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.0,
    unpaidBet: 0.0,
    eWalletPromotion: "",
  },
  {
    username: "Congtau",
    loginName: "Congtau",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.0,
    unpaidBet: 0.0,
    eWalletPromotion: "Lucky Spin",
  },
  {
    username: "hoangmjnh1",
    loginName: "hoangmjnh1",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.54,
    unpaidBet: 0.0,
    eWalletPromotion: "Register Bonus",
  },
  {
    username: "datui999",
    loginName: "datui999",
    lastName: "***",
    firstName: "***",
    currency: "VND",
    cashBalance: 0.0,
    unpaidBet: 0.0,
    eWalletPromotion: "None",
  },
//   {
//     username: "bilabi",
//     loginName: "bilabi",
//     lastName: "***",
//     firstName: "***",
//     currency: "VND",
//     cashBalance: 0.0,
//     unpaidBet: 0.0,
//     eWalletPromotion: "None",
//   },
//   {
//     username: "Yeuyeu20",
//     loginName: "Yeuyeu20",
//     lastName: "***",
//     firstName: "***",
//     currency: "VND",
//     cashBalance: 8.41,
//     unpaidBet: 0.0,
//     eWalletPromotion: "Register Bonus",
//   },
//   {
//     username: "MarktestMYR",
//     loginName: "MarktestMYR",
//     lastName: "***",
//     firstName: "***",
//     currency: "MYR",
//     cashBalance: 0.0,
//     unpaidBet: 0.0,
//     eWalletPromotion: "Promotion A",
//   },
//   {
//     username: "MarktestINR",
//     loginName: "MarktestINR",
//     lastName: "***",
//     firstName: "***",
//     currency: "INR",
//     cashBalance: 0.0,
//     unpaidBet: 0.0,
//     eWalletPromotion: "Promotion B",
//   },
//   {
//     username: "spfbdvp",
//     loginName: "spfbdvp",
//     lastName: "***",
//     firstName: "***",
//     currency: "VND",
//     cashBalance: 0.0,
//     unpaidBet: 0.0,
//     eWalletPromotion: "Register Bonus",
//   },
//   {
//     username: "tester123",
//     loginName: "tester123",
//     lastName: "***",
//     firstName: "***",
//     currency: "USD",
//     cashBalance: 3.21,
//     unpaidBet: 1.0,
//     eWalletPromotion: "Deposit Bonus",
//   },
//   {
//     username: "lucidmoon",
//     loginName: "lucidmoon",
//     lastName: "***",
//     firstName: "***",
//     currency: "VND",
//     cashBalance: 2.45,
//     unpaidBet: 0.0,
//     eWalletPromotion: "Cashback",
//   },
//   {
//     username: "nightowl",
//     loginName: "nightowl",
//     lastName: "***",
//     firstName: "***",
//     currency: "USD",
//     cashBalance: 1.0,
//     unpaidBet: 0.5,
//     eWalletPromotion: "Welcome Offer",
//   },
//   {
//     username: "moonlight",
//     loginName: "moonlight",
//     lastName: "***",
//     firstName: "***",
//     currency: "VND",
//     cashBalance: 0.0,
//     unpaidBet: 2.0,
//     eWalletPromotion: "Register Bonus",
//   },
];
