import type { Payment } from "./ListAccount";

export const dataListAccount: Payment[] = [
  {
    id: "1",
    status: "success",
    email: "user1@example.com",
    amount: 1000,
    accountType: "Thường",
    username: "Nguyễn Văn A",
    parentAgent: "Đại lý miền Bắc",
    loginName: "nguyenvana",
    introduction: "Bạn bè giới thiệu",
    totalPlayers: 10,
    vip: true,
    cardName: "Vietcombank",
    state: "Đang hoạt động",
    paused: false,
    currency: "VND",
    wantsToDeposit: true,
    firstDepositTime: "2025-01-01 08:00:00",
    firstDepositAmount: 500000,
    lastName: "Nguyễn",
    firstName: "Văn A",
    fullName: "Nguyễn Văn A",
    userBankName: "Nguyễn Văn A",
    userBankAccount: "123456789",
    bankOption: "Vietcombank",
    phone: "0901234567",
    emailRepeated: "user1@example.com",
    createdAt: "2024-12-25 10:00:00",
    lastLoginTime: "2025-07-12 10:00:00",
    registeredIp: "192.168.1.1",
    lastLoginIp: "192.168.1.100",
    nationality: "Việt Nam",
    domainRegister: "example.vn",
  },
  {
    id: "2",
    status: "processing",
    email: "user2@example.com",
    amount: 750,
    accountType: "VIP",
    username: "Trần Thị B",
    parentAgent: "Đại lý miền Trung",
    loginName: "tranthib",
    introduction: "Quảng cáo Facebook",
    totalPlayers: 5,
    vip: true,
    cardName: "Techcombank",
    state: "Đang xử lý",
    paused: false,
    currency: "USD",
    wantsToDeposit: false,
    firstDepositTime: "2025-01-10 09:15:00",
    firstDepositAmount: 200000,
    lastName: "Trần",
    firstName: "Thị B",
    fullName: "Trần Thị B",
    userBankName: "Trần Thị B",
    userBankAccount: "234567891",
    bankOption: "Techcombank",
    phone: "0912345678",
    emailRepeated: "user2@example.com",
    createdAt: "2025-01-05 11:00:00",
    lastLoginTime: "2025-07-11 08:30:00",
    registeredIp: "192.168.1.2",
    lastLoginIp: "192.168.1.101",
    nationality: "Việt Nam",
    domainRegister: "abc.vn",
  },
  {
    id: "3",
    status: "failed",
    email: "user3@example.com",
    amount: 0,
    accountType: "Thường",
    username: "Lê Văn C",
    parentAgent: "Đại lý miền Nam",
    loginName: "levanc",
    introduction: "Tự đăng ký",
    totalPlayers: 0,
    vip: false,
    cardName: "MB Bank",
    state: "Tạm dừng",
    paused: true,
    currency: "VND",
    wantsToDeposit: false,
    firstDepositTime: "2025-02-01 14:00:00",
    firstDepositAmount: 0,
    lastName: "Lê",
    firstName: "Văn C",
    fullName: "Lê Văn C",
    userBankName: "Lê Văn C",
    userBankAccount: "345678912",
    bankOption: "MB Bank",
    phone: "0923456789",
    emailRepeated: "user3@example.com",
    createdAt: "2025-01-28 13:00:00",
    lastLoginTime: "2025-06-30 17:00:00",
    registeredIp: "192.168.1.3",
    lastLoginIp: "192.168.1.102",
    nationality: "Việt Nam",
    domainRegister: "leuser.vn",
  },
  {
    id: "4",
    status: "pending",
    email: "user4@example.com",
    amount: 200,
    accountType: "VIP",
    username: "Phạm D",
    parentAgent: "Đại lý miền Tây",
    loginName: "phamd",
    introduction: "Qua đối tác",
    totalPlayers: 2,
    vip: true,
    cardName: "ACB",
    state: "Chờ duyệt",
    paused: false,
    currency: "USD",
    wantsToDeposit: true,
    firstDepositTime: "2025-03-01 12:00:00",
    firstDepositAmount: 150000,
    lastName: "Phạm",
    firstName: "D",
    fullName: "Phạm D",
    userBankName: "Phạm D",
    userBankAccount: "456789123",
    bankOption: "ACB",
    phone: "0934567890",
    emailRepeated: "user4@example.com",
    createdAt: "2025-02-20 10:30:00",
    lastLoginTime: "2025-07-10 16:00:00",
    registeredIp: "192.168.1.4",
    lastLoginIp: "192.168.1.103",
    nationality: "Việt Nam",
    domainRegister: "vipdomain.vn",
  },
  {
    id: "5",
    status: "success",
    email: "user5@example.com",
    amount: 1200,
    accountType: "Thường",
    username: "Đỗ Thị E",
    parentAgent: "Đại lý miền Bắc",
    loginName: "dothie",
    introduction: "Từ sự kiện",
    totalPlayers: 8,
    vip: false,
    cardName: "Sacombank",
    state: "Hoạt động",
    paused: false,
    currency: "VND",
    wantsToDeposit: true,
    firstDepositTime: "2025-04-01 08:30:00",
    firstDepositAmount: 300000,
    lastName: "Đỗ",
    firstName: "Thị E",
    fullName: "Đỗ Thị E",
    userBankName: "Đỗ Thị E",
    userBankAccount: "567891234",
    bankOption: "Sacombank",
    phone: "0945678912",
    emailRepeated: "user5@example.com",
    createdAt: "2025-03-25 09:00:00",
    lastLoginTime: "2025-07-12 12:30:00",
    registeredIp: "192.168.1.5",
    lastLoginIp: "192.168.1.104",
    nationality: "Việt Nam",
    domainRegister: "dotrung.vn",
  },
];
